# 常用的综合评价数学模型

综合评价数学模型就是将同一评价对象不同方面的多个指标值综合在一起, 得到一个整体性评价指标值的一个数学表达式. 通常根据评价的特点与需要来选择合适的综合评价数学模型. 针对 $n$ 个评价对象, $m$ 个评价指标 $x_1, x_2, \cdots, x_m$, 第 $i\ (i = 1, 2, \cdots, n)$ 个评价对象的指标值 $\boldsymbol{a}_i = [a_{i1}, a_{i2}, \cdots, a_{im}]$, 经过预处理的指标值为 $\boldsymbol{b}_i = [b_{i1}, b_{i2}, \cdots, b_{im}]$.


**例 9.2** (续例 9.1) 采用比例变换法得到的评价矩阵
$$
\boldsymbol{R}_2 = 
\begin{bmatrix}
0.8 & 0.5556 & 0.9524 & 0.8182 & 0.7143 & 1 \\
1 & 1 & 0.8571 & 0.6923 & 0.4286 & 0.5 \\
0.72 & 0.7407 & 1 & 1 & 1 & 0.7 \\
0.88 & 0.6667 & 0.9524 & 0.9 & 0.7143 & 0.5
\end{bmatrix}
$$
作为标准化数据矩阵 $\boldsymbol{B} = (b_{ij})_{4 \times 6}$, 分别利用 TOPSIS 法、灰色关联度、熵值法与秩和比法对战斗机的性能进行综合评价.

### 1. 利用 TOPSIS 法进行综合评价
(1) 确定正理想和负理想解分别为
$$
\boldsymbol{C}^+ = [1, 1, 1, 1, 1, 1],
$$
$$
\boldsymbol{C}^- = [0.72, 0.5556, 0.8571, 0.6923, 0.4286, 0.5].
$$
(2) 由计算公式
$$
s_i^+ = \sqrt{\sum_{j=1}^6 (b_{ij} - c_j^+)^2},\quad s_i^- = \sqrt{\sum_{j=1}^6 (b_{ij} - c_j^-)^2},\quad i = 1, 2, 3, 4,
$$
计算各评价对象到正理想解和负理想解的距离分别为
$$
s^+ = [0.5954, 0.8316, 0.4854, 0.6851],
$$
$$
s^- = [0.6025, 0.5253, 0.7183, 0.4145].
$$
(3) 由公式
$$
f_i = \frac{s_i^-}{s_i^- + s_i^+},\quad i = 1, 2, 3, 4.
$$
计算各机型对理想解的相对接近度为
$$
\boldsymbol{F} = [f_1, f_2, f_3, f_4] = [0.5029, 0.3871, 0.5967, 0.3769]
$$
(4)根据相对接近度对各机型按优劣次序排序如下：
$$
A_3 > A_1 > A_2 > A_4.
$$

### 2. 灰色关联度评价
(1) 灰色关联度的计算数据如表 9.5 所示.

**表 9.5** 灰色关联系数及关联度计算数据

|  | 最大速度 $x_1$ | 飞行半径 $x_2$ | 最大负载 $x_3$ | 费用 $x_4$ | 可靠性 $x_5$ | 灵敏度 $x_6$ | $r_i$ |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| $A_1$ | $0.5882$ | $0.3913$ | $0.8571$ | $0.6111$ | $0.5$ | $1$ | $0.6580$ |
| $A_2$ | $1$ | $1$ | $0.6667$ | $0.4815$ | $0.3333$ | $0.3636$ | $0.6409$ |
| $A_3$ | $0.5051$ | $0.5243$ | $1$ | $1$ | $1$ | $0.4878$ | $0.7529$ |
| $A_4$ | $0.7042$ | $0.4615$ | $0.8571$ | $0.7407$ | $0.5$ | $0.3636$ | $0.6045$ |

(2) 根据灰色关联度对各机型按优劣次序排序如下
$$
A_3 > A_1 > A_2 > A_4.
$$

### 3. 熵值法
(1) 利用公式
$$
p_{ij} = \frac{b_{ij}}{\sum_{i=1}^4 b_{ij}}\quad (i = 1, 2, 3, 4;\ j = 1, 2, \cdots, 6).
$$
求各指标的特征比重为
$$
\boldsymbol{P} = 
\begin{bmatrix}
0.2353 & 0.1875 & 0.2532 & 0.2399 & 0.25 & 0.3704 \\
0.2941 & 0.3375 & 0.2278 & 0.2030 & 0.15 & 0.1852 \\
0.2118 & 0.25 & 0.2658 & 0.2932 & 0.35 & 0.2593 \\
0.2588 & 0.225 & 0.2532 & 0.2639 & 0.25 & 0.1852
\end{bmatrix}.
$$
(2) 利用公式
$$
e_j = -\frac{1}{\ln 4} \sum_{i=1}^4 p_{ij} \ln p_{ij}\quad (j = 1, 2, \cdots, 6),
$$
计算各指标的熵值为
$$
\boldsymbol{e} = [e_1, e_2, \cdots, e_6] = [0.9947, 0.9829, 0.9989, 0.9936, 0.9703, 0.9684].
$$
(3) 利用公式
$$
g_j = 1 - e_j\quad (j = 1, 2, \cdots, 6),
$$
计算各指标的差异系数为
$$
\boldsymbol{g} = [g_1, g_2, \cdots, g_6] = [0.0053, 0.0171, 0.0011, 0.0064, 0.0297, 0.0316].
$$
(4) 由公式
$$
w_j = \frac{g_j}{\sum_{k=1}^6 g_k}\quad (j = 1, 2, \cdots, 6),
$$
求得各指标的权重向量为
$$
\boldsymbol{W}_2 = [w_1, w_2, \cdots, w_6] = [0.0583, 0.1870, 0.0122, 0.0700, 0.3255, 0.3470].
$$
(5) 计算第 $i$ 个评价对象的综合评价值
$$
f_i = \sum_{j=1}^6 w_j p_{ij},\quad i = 1, 2, 3, 4,
$$
得 $4$ 个评价对象的评价值向量
$$
\boldsymbol{F} = [f_1, f_2, f_3, f_4] = [0.2785, 0.2103, 0.2868, 0.2244],
$$
各机型按优劣次序排序如下
$$
A_3 > A_1 > A_4 > A_2.
$$

### 4. 利用秩和比法进行综合评价
#### 1) 编秩

对于各机型的评价指标进行编秩, 结果如表 9.6 所示.

**表 9.6** 各机型指标值的编秩值

|  | 最大速度 $x_1$ | 飞行半径 $x_2$ | 最大负载 $x_3$ | 费用 $x_4$ | 可靠性 $x_5$ | 灵敏度 $x_6$ |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| $A_1$ | $2$ | $1$ | $2.5$ | $2$ | $2.5$ | $4$ |
| $A_2$ | $4$ | $4$ | $1$ | $1$ | $1$ | $1.5$ |
| $A_3$ | $1$ | $3$ | $4$ | $4$ | $4$ | $3$ |
| $A_4$ | $3$ | $2$ | $2.5$ | $3$ | $2.5$ | $1.5$ |

#### 2) 计算秩和比

用公式 $\text{RSR}_i = \sum_{j=1}^6 w_j R_{ij} / 4,\ i = 1, 2, 3, 4$, 这里取 $w_j = \frac{1}{6}\ (j = 1, 2, \cdots, 6)$, 计算加权秩和比为
$$
\text{RSR} = [0.5833, 0.5208, 0.7917, 0.6042].
$$
#### 3) 秩和比排序

根据 $\text{RSR}_i\ (i = 1, 2, 3, 4)$ 对 $4$ 种机型的性能按优劣次序排序为
$$
A_3 > A_4 > A_1 > A_2.
$$

In [ ]:
# 代码实现
import numpy as np
from scipy.stats import rankdata

a = np.loadtxt("Pdata9_1_3.txt")  # 读取比例变换得到的评价矩阵

# TOPSIS法
print(f"-------------------TOPSIS法-------------------------")
c_plus = a.max(axis=0)  # 逐列求最大值
c_minus = a.min(axis=0)  # 逐列求最小值
print(f"正理想解: {c_plus} \n负理想解: {c_minus}")
d1 = np.linalg.norm(a-c_plus, axis=1)  # 求到正理想解的距离
d2 = np.linalg.norm(a-c_minus, axis=1)  # 求到负理想解的距离
print(f"到正理想解的距离：{d1} \n到负理想解的距离: {d2}")  # 显示到正理想解和服理想解的距离
f1 = d2 / (d1 + d2)  # 计算各评价对象对理想解的接近度
print(f"TOPSIS的评价值为: {f1}")

# 灰色关联度分析
print(f"-------------------灰色关联度分析-------------------------")
t = c_plus - a  # 计算参考序列与每个序列的差
print(t)
m_min = t.min()  # 计算两级最小差
m_max = t.max()  # 计算两级最大差
print(f"两级最小差: {m_min}\n两级最大差: {m_max}")
rho = 0.5  # 分辨系数
xs = (m_min + rho * m_max) / (t + rho * m_max)  #计算灰色关联系数
f2 = xs.mean(axis=1)  # 计算灰色关联度，权重取1/6
print(f"关联系数=\n{xs} \n关联度(f2)={f2}")

# 熵值法
print(f"-------------------熵值法-------------------------")
[n, m] = a.shape
c_sum = a.sum(axis=0)  # 逐列求和
P = 1 / c_sum * a  # 求特征比重矩阵
e = - (P * np.log(P)).sum(axis=0) / np.log(n)  # 计算熵值
g = 1 - e  # 计算差异系数
w = g / sum(g)  # 计算权重系数, w为1x6行向量
f3 = P @ w  # 计算各评价对象的评价值
print(f"P(特征比重矩阵)=\n{P} \ne(熵值)={e} \ng(差异系数)={g} \nw(比例权重)={w} \nf3(评价值)={f3}")

# 秩和比法(RSR)
print(f"-------------------秩和比法(RSR)-------------------------")
R = [rankdata(a[:, i]) for i in np.arange(6)]  # 求每一列的秩
R = np.array(R).T  # 构造秩矩阵
print(f"秩矩阵为:\n{R}")
RSR = R.mean(axis=1) / n
print(f"RSR={RSR}")


-------------------TOPSIS法-------------------------
正理想解: [1. 1. 1. 1. 1. 1.] 
负理想解: [0.72       0.55555556 0.85714286 0.69230769 0.42857143 0.5       ]
到正理想解的距离：[0.59538974 0.83163293 0.48540227 0.685136  ] 
到负理想解的距离: [0.60245103 0.52529122 0.71826658 0.4144692 ]
TOPSIS的评价值为: [0.50294751 0.38711907 0.59673105 0.37692547]
-------------------灰色关联度分析-------------------------
[[0.2        0.44444444 0.04761905 0.18181818 0.28571429 0.        ]
 [0.         0.         0.14285714 0.30769231 0.57142857 0.5       ]
 [0.28       0.25925926 0.         0.         0.         0.3       ]
 [0.12       0.33333333 0.04761905 0.1        0.28571429 0.5       ]]
两级最小差: 0.0
两级最大差: 0.5714285714285714
关联系数=
[[0.58823529 0.39130435 0.85714286 0.61111111 0.5        1.        ]
 [1.         1.         0.66666667 0.48148148 0.33333333 0.36363636]
 [0.50505051 0.52427184 1.         1.         1.         0.48780488]
 [0.70422535 0.46153846 0.85714286 0.74074074 0.5        0.36363636]] 
关联度(f2)=[0.6579656  0.6408