# 模糊综合评价

例 14.11 某校规定, 在对一位教师的评价中, 若 “好” 与 “较好” 占 50%以上, 可晋升为教授, 教授分教学型教授和科研型教授, 在评价指标上给出不同的权重, 分别为 $ \boldsymbol{W}_1 = [0.2, 0.5, 0.1, 0.2] $, $ \boldsymbol{W}_2 = [0.2, 0.1, 0.5, 0.2] $. 学科评议组由 7 人组成, 对某教师的评价见表 14.3, 请判别该教师能否晋升, 可晋升为哪一级教授.

**表 14.3 对某教师的评价数据**

|  | 好 | 较好 | 一般 | 较差 | 差 |
| :---: | :---: | :---: | :---: | :---: | :---: |
| 政治表现 | 4 | 2 | 1 | 0 | 0 |
| 教学水平 | 6 | 1 | 0 | 0 | 0 |
| 科研水平 | 0 | 0 | 5 | 1 | 1 |
| 外语水平 | 2 | 2 | 1 | 1 | 1 |

解 将评议组 7 人对每一项的投票按百分比转化成隶属度得综合评判矩阵:
$$
\boldsymbol{R} = \begin{bmatrix} 
0.5714 & 0.2857 & 0.1429 & 0 & 0 \\
0.8571 & 0.1429 & 0 & 0 & 0 \\
0 & 0 & 0.7143 & 0.1429 & 0.1429 \\
0.2857 & 0.2857 & 0.1429 & 0.1429 & 0.1429 
\end{bmatrix}.
$$

按合成 $ M(\cdot, +) $ 算子, 即通常的加权求和, 得到综合评价值
$$
\boldsymbol{A}_1 = \boldsymbol{W}_1 \circ \boldsymbol{R} = [0.6, 0.1857, 0.1286, 0.0429, 0.0429],
$$
$$
\boldsymbol{A}_2 = \boldsymbol{W}_2 \circ \boldsymbol{R} = [0.2571, 0.1286, 0.4143, 0.1, 0.1].
$$

显然, 对第一类权重 “好” 与 “较好” 占 50%以上, 故该教师可晋升为教学型教授.

In [2]:
import numpy as np

vote = np.array([[4, 2, 1, 0, 0],
                 [6, 1, 0, 0, 0],
                 [0, 0, 5, 1, 1],
                 [2, 2, 1, 1, 1]])
rate = vote / 7
W1 = np.array([0.2, 0.5, 0.1, 0.2])
W2 = np.array([0.2, 0.1, 0.5, 0.2])
A1 = np.dot(W1, rate)
A2 = np.dot(W2, rate)

print(f"综合评价矩阵:\n{rate}\n")
print(f"权重1的综合评价向量:\n{A1}")
print(f"权重2的综合评价向量:\n{A2}")

综合评价矩阵:
[[0.57142857 0.28571429 0.14285714 0.         0.        ]
 [0.85714286 0.14285714 0.         0.         0.        ]
 [0.         0.         0.71428571 0.14285714 0.14285714]
 [0.28571429 0.28571429 0.14285714 0.14285714 0.14285714]]

权重1的综合评价向量:
[0.6        0.18571429 0.12857143 0.04285714 0.04285714]
权重2的综合评价向量:
[0.25714286 0.12857143 0.41428571 0.1        0.1       ]


例 14.12 某产粮区进行耕作制度改革, 制订了甲、乙、丙三个方案见表 14.4, 以表 14.5 作为评价指标, 5 个指标的权重向量定为 $[0.2, 0.1, 0.15, 0.3, 0.25]$, 请确定应该选择哪一个方案.

**表 14.4 三个方案**

| 方案 | 亩产量 | 产品质量 | 亩用工量 | 亩纯收入 | 生态影响 |
| :---: | :---: | :---: | :---: | :---: | :---: |
| 甲 | 592.5 | 3 | 55 | 72 | 5 |
| 乙 | 529 | 2 | 38 | 105 | 3 |
| 丙 | 412 | 1 | 32 | 85 | 2 |

**表 14.5 5 个评价指标**

| 分数 | 亩产量 | 产品质量 | 亩用工量 | 亩纯收入 | 生态影响 |
| :---: | :---: | :---: | :---: | :---: | :---: |
| 5 | 550~600 | 1 | ≤20 | ≥130 | 1 |
| 4 | 500~550 | 2 | 20~30 | 110~130 | 2 |
| 3 | 450~500 | 3 | 30~40 | 90~110 | 3 |
| 2 | 400~450 | 4 | 40~50 | 70~90 | 4 |
| 1 | 350~400 | 5 | 50~60 | 50~70 | 5 |
| 0 | ≤350 | 6 | ≥60 | ≤50 | 6 |

解 根据评价标准建立各指标的隶属函数如下.

(1) 亩产量的隶属函数:
$$
c_1(x_1) = 
\begin{cases} 
0, & x_1 \leq 350, \\
\dfrac{x_1 - 350}{600 - 350}, & 350 < x_1 < 600, \\
1, & x_1 \geq 600.
\end{cases}
$$

(2) 产品质量的隶属函数:
$$
c_2(x_2) = 
\begin{cases} 
1, & x_2 \leq 1, \\
1 - \dfrac{x_2 - 1}{6 - 1}, & 1 < x_2 < 6, \\
0, & x_2 \geq 6.
\end{cases}
$$

(3) 亩用工量的隶属函数:
$$
c_3(x_3) = 
\begin{cases} 
1, & x_3 \leq 20, \\
1 - \dfrac{x_3 - 20}{60 - 20}, & 20 < x_3 < 60, \\
0, & x_3 \geq 60.
\end{cases}
$$

(4) 亩纯收入的隶属函数:
$$
c_4(x_4) = 
\begin{cases} 
0, & x_4 \leq 50, \\
\dfrac{x_4 - 50}{130 - 50}, & 50 < x_4 < 130, \\
1, & x_4 \geq 130.
\end{cases}
$$

(5) 对生态影响的隶属函数:
$$
c_5(x_5) = 
\begin{cases} 
1, & x_5 \leq 1, \\
1 - \dfrac{x_5 - 1}{6 - 1}, & 1 < x_5 < 6, \\
0, & x_5 \geq 6.
\end{cases}
$$

将表 14.4 三个方案中的数据代入相应隶属函数算出隶属度, 从而得到综合评判矩阵:
$$
\boldsymbol{R} = \begin{bmatrix} 
0.97 & 0.716 & 0.248 \\
0.6 & 0.8 & 1 \\
0.125 & 0.55 & 0.7 \\
0.275 & 0.6875 & 0.4375 \\
0.2 & 0.6 & 0.8 
\end{bmatrix}.
$$

根据所给权重向量, 进行加权求和得
$$
\boldsymbol{A} = \boldsymbol{W} \circ \boldsymbol{R} = [0.40525, 0.66195, 0.58585].
$$

根据最大隶属度原则, 0.66195 最大, 所对应的是乙方案, 故应选择乙方案.

In [8]:
import numpy as np

data = np.array([[592.5, 3, 55, 72, 5],
                 [529, 2, 38, 105, 3],
                 [412, 1, 32, 85, 2]])
data = data.T
# 隶属函数
c1 = lambda x: np.piecewise(x, [(350 < x) & (x < 600), x >= 600], [lambda x: (x - 350) / 250, 1])  # 没定义的等于0
c2 = lambda x: np.piecewise(x, [(1 < x) & (x < 6), x <= 1], [lambda x: 1 - (x - 1) / 5, 1])
c3 = lambda x: np.piecewise(x, [(20 < x) & (x < 60), x <= 20], [lambda x: 1 - (x - 20) / 40, 1])
c4 = lambda x: np.piecewise(x, [(50 < x) & (x < 130), x >= 130], [lambda x: (x - 50) / 80, 1])
c5 = lambda x: np.piecewise(x, [(1 < x) & (x < 6), x <= 1], [lambda x: 1 - (x - 1) / 5, 1])

R = np.c_[c1(data[0]), c2(data[1]), c3(data[2]), c4(data[3]), c5(data[4])]  # 综合评价矩阵(3, 5)

W = np.array([0.2, 0.1, 0.15, 0.3, 0.25])

A = np.dot(W, R.T)

print(f"综合评价矩阵:\n{R}\n")
print(f"综合评价向量:\n{A}")


综合评价矩阵:
[[0.97   0.6    0.125  0.275  0.2   ]
 [0.716  0.8    0.55   0.6875 0.6   ]
 [0.248  1.     0.7    0.4375 0.8   ]]

综合评价向量:
[0.40525 0.66195 0.58585]
